import React, { useEffect, useState, useCallback } from 'react';
import { fetchWeatherForecast } from './services/geminiService';
import { WeatherResponse, WeatherDay, GroundingChunk } from './types';
import { DailyCard } from './components/DailyCard';
import { TemperatureChart } from './components/TemperatureChart';
import { 
  MapPin, 
  RefreshCw, 
  ExternalLink, 
  Loader2, 
  Info, 
  AlertTriangle, 
  ShieldCheck, 
  Wallet, 
  CheckCircle, 
  X,
  Sparkles,
  BrainCircuit
} from 'lucide-react';

const App: React.FC = () => {
  const [weatherData, setWeatherData] = useState<WeatherDay[]>([]);
  const [weeklyOverview, setWeeklyOverview] = useState<string>("");
  const [sources, setSources] = useState<GroundingChunk[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);
  const [showCostModal, setShowCostModal] = useState<boolean>(false);

  const loadWeather = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data: WeatherResponse = await fetchWeatherForecast("Isle of Wight");
      if (data.forecast.length === 0) {
        setError("Could not retrieve forecast data at this time. Please try again.");
      } else {
        setWeatherData(data.forecast);
        setWeeklyOverview(data.weeklyOverview);
        setSources(data.groundingChunks);
        setLastUpdated(new Date());
      }
    } catch (err: any) {
      if (err.message?.includes('429') || err.status === 429) {
        setError("Free tier request limit reached. Please wait a moment and try again.");
      } else {
        setError("Unable to fetch weather data. Please check your connection.");
      }
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadWeather();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="min-h-screen bg-slate-900 text-white selection:bg-blue-500/30 relative">
      
      {/* Navbar / Header */}
      <header className="sticky top-0 z-40 backdrop-blur-lg bg-slate-900/80 border-b border-slate-800">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-gradient-to-tr from-blue-600 to-purple-600 rounded-lg shadow-lg shadow-blue-500/20">
              <MapPin className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="font-bold text-lg tracking-tight flex items-center gap-2">
                WightWeather <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-blue-500 text-white uppercase tracking-wide">Pro</span>
              </h1>
              <p className="text-xs text-slate-400 hidden sm:block">AI-Powered Tourism Intelligence</p>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            <button 
              onClick={() => setShowCostModal(true)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-green-500/10 hover:bg-green-500/20 text-green-400 rounded-full text-xs font-medium border border-green-500/20 transition-colors"
            >
              <ShieldCheck className="w-3.5 h-3.5" />
              <span className="hidden xs:inline">Free Tier Active</span>
            </button>

            <button 
              onClick={loadWeather}
              disabled={loading}
              className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded-full text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed border border-slate-700"
            >
              <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
              <span className="hidden sm:inline">{loading ? 'Analyze' : 'Refresh'}</span>
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        
        {/* Hero Section */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
          <div>
            <h2 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-200 via-cyan-200 to-white">
              Isle of Wight Intelligence
            </h2>
            <p className="text-slate-400 mt-2 flex items-center gap-2 max-w-2xl">
              <Sparkles className="w-4 h-4 text-purple-400" />
              Real-time analysis for Sailing, Beach activities, and Ferry reliability generated by Gemini 2.5.
            </p>
          </div>
          {lastUpdated && (
            <p className="text-xs text-slate-500">
              Analysis generated: {lastUpdated.toLocaleTimeString()}
            </p>
          )}
        </div>

        {/* Error State */}
        {error && !loading && (
          <div className="p-4 rounded-xl bg-red-900/20 border border-red-800/50 text-red-200 flex items-center gap-3">
            <AlertTriangle className="w-6 h-6 text-red-400 flex-shrink-0" />
            <div>
              <p className="font-medium">{error}</p>
              <button onClick={loadWeather} className="text-sm underline hover:text-red-100 mt-1">
                Retry Analysis
              </button>
            </div>
          </div>
        )}

        {/* Content */}
        {loading ? (
          <div className="h-96 flex flex-col items-center justify-center text-slate-400 gap-4">
            <Loader2 className="w-10 h-10 animate-spin text-blue-500" />
            <div className="text-center space-y-2">
              <p className="font-medium text-white">Generating AI Analysis...</p>
              <p className="text-sm">Reviewing ferry schedules, wind conditions, and tourist suitability.</p>
            </div>
          </div>
        ) : (
          <>
             {/* Executive Summary & Chart Grid */}
            {weatherData.length > 0 && (
               <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                 {/* Executive Summary Box */}
                 <div className="lg:col-span-3 bg-gradient-to-r from-slate-800/80 to-slate-900/80 border border-slate-700 rounded-2xl p-6 relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3 pointer-events-none"></div>
                    <div className="flex items-start gap-4 relative z-10">
                      <div className="p-3 bg-blue-500/20 rounded-xl text-blue-300 hidden sm:block">
                        <BrainCircuit className="w-6 h-6" />
                      </div>
                      <div className="flex-1">
                        <h3 className="text-lg font-bold text-white mb-2 flex items-center gap-2">
                          <BrainCircuit className="w-5 h-5 text-blue-400 sm:hidden" />
                          Executive Summary
                        </h3>
                        <p className="text-slate-300 leading-relaxed text-sm md:text-base">
                          {weeklyOverview}
                        </p>
                      </div>
                    </div>
                 </div>

                 <div className="lg:col-span-2">
                   <TemperatureChart data={weatherData} />
                 </div>
                 
                 <div className="lg:col-span-1 h-full">
                    <DailyCard dayData={weatherData[0]} isToday={true} />
                 </div>
               </div>
            )}

            {/* Rest of the Week Grid */}
            {weatherData.length > 0 && (
              <div>
                <h3 className="text-xl font-semibold text-slate-200 mb-4">7-Day Outlook</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                  {weatherData.slice(1).map((day, index) => (
                    <DailyCard key={index} dayData={day} />
                  ))}
                </div>
              </div>
            )}

            {/* Sources Footer */}
            {sources.length > 0 && (
              <div className="pt-8 border-t border-slate-800">
                <h4 className="text-sm font-semibold text-slate-500 mb-3">Verified Data Sources</h4>
                <div className="flex flex-wrap gap-2">
                  {sources.map((source, idx) => (
                    <a 
                      key={idx}
                      href={source.web?.uri}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-1 px-3 py-1.5 rounded-md bg-slate-800 hover:bg-slate-700 text-xs text-slate-300 transition-colors border border-slate-700 max-w-xs truncate"
                    >
                      <ExternalLink className="w-3 h-3 shrink-0" />
                      <span className="truncate">{source.web?.title || source.web?.uri}</span>
                    </a>
                  ))}
                </div>
              </div>
            )}
          </>
        )}
      </main>

      {/* Cost Assurance Modal */}
      {showCostModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/80 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-slate-800 border border-slate-700 rounded-2xl max-w-md w-full shadow-2xl relative p-6">
            <button 
              onClick={() => setShowCostModal(false)}
              className="absolute top-4 right-4 text-slate-400 hover:text-white transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
            
            <div className="flex items-center gap-3 mb-6">
              <div className="p-3 bg-green-500/10 rounded-xl">
                <Wallet className="w-6 h-6 text-green-400" />
              </div>
              <h3 className="text-xl font-bold text-white">Free Tier Active</h3>
            </div>

            <div className="space-y-4">
              <p className="text-slate-300">
                This intelligent prototype is running on the <span className="text-green-400 font-semibold">Google AI Studio Free Tier</span>.
              </p>

              <div className="bg-slate-900/50 rounded-xl p-4 space-y-3 border border-slate-700/50">
                <div className="flex items-center gap-3">
                  <CheckCircle className="w-5 h-5 text-green-400 shrink-0" />
                  <div>
                    <p className="text-sm font-medium text-slate-200">Zero Cost</p>
                    <p className="text-xs text-slate-500">Uses 'gemini-2.5-flash' (Free).</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <CheckCircle className="w-5 h-5 text-green-400 shrink-0" />
                  <div>
                    <p className="text-sm font-medium text-slate-200">Agentic Features</p>
                    <p className="text-xs text-slate-500">Sailing/Ferry analysis included in prompt.</p>
                  </div>
                </div>
              </div>
              
              <button 
                onClick={() => setShowCostModal(false)}
                className="w-full mt-6 py-2.5 bg-green-600 hover:bg-green-500 text-white rounded-xl font-medium transition-colors"
              >
                Return to Dashboard
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default App;